package main

import (
	"fmt"
	"strconv"
	"strings"
)

const (
	errXaddIDMustBeGreaterThanZeroZero = "-ERR The ID specified in XADD must be greater than 0-0\r\n"
	errXaddIDEqualOrSmallerThanTop     = "-ERR The ID specified in XADD is equal or smaller than the target stream top item\r\n"
	zeroEntryID                        = "0-0"
	autoGeneratedSequenceWildcard      = "*"
	xrangeEndOfStreamSentinel          = "+"
	startSequenceNumberDefault         int64 = 0
	endSequenceNumberDefault           int64 = 9223372036854775807
)

type StreamEntry struct {
	ID          string
	Fields      map[string]string
	FieldValues []string
}

// XrangeEntryResponse is one XRANGE result row: the entry ID and its field/value
// bulk strings in the order they were added (key1, value1, key2, value2, ...).
type XrangeEntryResponse struct {
	EntryID     string
	FieldValues []string
}

// XrangeResponse is the full XRANGE result: an array of entries.
type XrangeResponse struct {
	Entries []XrangeEntryResponse
}

// XreadEntryResponse is one XREAD result entry: ID plus ordered field/value bulk strings.
type XreadEntryResponse struct {
	EntryID     string
	FieldValues []string
}

// XreadStreamResponse is one stream block in an XREAD result.
type XreadStreamResponse struct {
	StreamKey string
	Entries   []XreadEntryResponse
}

// XreadResponse is the full XREAD result: an array of streams.
type XreadResponse struct {
	Streams []XreadStreamResponse
}

type Stream struct {
	Entries []StreamEntry
}

func (c *Cache) AddStreamEntry(streamKey string, entryID string, fieldValues []string) {
	c.mutex.Lock()
	defer c.mutex.Unlock()

	fields := make(map[string]string, len(fieldValues)/2)
	for index := 0; index+1 < len(fieldValues); index += 2 {
		fields[fieldValues[index]] = fieldValues[index+1]
	}

	var stream *Stream
	item, exists := c.cache[streamKey]
	if exists {
		stream, _ = item.Value.(*Stream)
	}

	if stream == nil {
		stream = &Stream{Entries: []StreamEntry{}}
	}

	stream.Entries = append(stream.Entries, StreamEntry{
		ID:          entryID,
		Fields:      fields,
		FieldValues: append([]string(nil), fieldValues...),
	})

	c.cache[streamKey] = CacheItem{
		Value:      stream,
		Expiration: 0,
	}
}

func (c *Cache) GetStream(streamKey string) *Stream {
	c.mutex.RLock()
	defer c.mutex.RUnlock()

	item, exists := c.cache[streamKey]
	if !exists {
		return nil
	}

	stream, ok := item.Value.(*Stream)
	if !ok {
		return nil
	}

	return stream
}

func parseEntryID(entryID string) (milliseconds int64, sequence int64, err error) {
	parts := strings.Split(entryID, "-")
	if len(parts) != 2 {
		return 0, 0, fmt.Errorf("invalid entry id %q", entryID)
	}

	milliseconds, err = strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return 0, 0, err
	}

	sequence, err = strconv.ParseInt(parts[1], 10, 64)
	if err != nil {
		return 0, 0, err
	}

	return milliseconds, sequence, nil
}

func parseRangeBoundSequence(boundID string, defaultSequence int64) int64 {
	parts := strings.Split(boundID, "-")
	if len(parts) != 2 {
		return defaultSequence
	}

	sequence, err := strconv.ParseInt(parts[1], 10, 64)
	if err != nil {
		return defaultSequence
	}

	return sequence
}

func normalizeRangeBoundID(boundID string, defaultSequence int64) (string, error) {
	parts := strings.Split(boundID, "-")
	if len(parts) == 1 {
		milliseconds, err := strconv.ParseInt(parts[0], 10, 64)
		if err != nil {
			return "", err
		}

		return formatEntryID(milliseconds, defaultSequence), nil
	}

	if len(parts) == 2 {
		return boundID, nil
	}

	return "", fmt.Errorf("invalid range bound id %q", boundID)
}

func resolveXrangeEndBoundID(stream *Stream, endID string) (string, error) {
	if endID == xrangeEndOfStreamSentinel {
		if stream == nil || len(stream.Entries) == 0 {
			return "", fmt.Errorf("empty stream")
		}

		return lastStreamEntryID(stream), nil
	}

	return normalizeRangeBoundID(endID, endSequenceNumberDefault)
}

func entryIDInInclusiveRange(entryID string, startBoundID string, endBoundID string) bool {
	if entryIDGreaterThan(startBoundID, entryID) {
		return false
	}

	if entryIDGreaterThan(entryID, endBoundID) {
		return false
	}

	return true
}

func entryIDAfterExclusiveStart(entryID string, startBoundID string) bool {
	return entryIDGreaterThan(entryID, startBoundID)
}

func entryIDGreaterThan(leftEntryID string, rightEntryID string) bool {
	leftMilliseconds, leftSequence, err := parseEntryID(leftEntryID)
	if err != nil {
		return false
	}

	rightMilliseconds, rightSequence, err := parseEntryID(rightEntryID)
	if err != nil {
		return false
	}

	if leftMilliseconds > rightMilliseconds {
		return true
	}
	if leftMilliseconds < rightMilliseconds {
		return false
	}

	return leftSequence > rightSequence
}

func lastStreamEntryID(stream *Stream) string {
	if stream == nil || len(stream.Entries) == 0 {
		return zeroEntryID
	}

	return stream.Entries[len(stream.Entries)-1].ID
}

func isPartialAutoGeneratedEntryID(entryID string) bool {
	parts := strings.Split(entryID, "-")
	return len(parts) == 2 && parts[1] == autoGeneratedSequenceWildcard
}

func isFullyAutoGeneratedEntryId(entryID string) bool {
	if entryID != "*" {
		return false
	}

	return true
}

func formatEntryID(milliseconds int64, sequence int64) string {
	return fmt.Sprintf("%d-%d", milliseconds, sequence)
}

func nextSequenceNumberForMilliseconds(stream *Stream, milliseconds int64) int64 {
	maxSequence := int64(-1)

	if stream != nil {
		for _, entry := range stream.Entries {
			entryMilliseconds, sequence, err := parseEntryID(entry.ID)
			if err != nil || entryMilliseconds != milliseconds {
				continue
			}
			if sequence > maxSequence {
				maxSequence = sequence
			}
		}
	}

	if maxSequence < 0 {
		if milliseconds == 0 {
			return 1
		}
		return 0
	}

	return maxSequence + 1
}

func resolveStreamEntryID(stream *Stream, entryID string) string {
	if isFullyAutoGeneratedEntryId(entryID) {
		milliseconds := CurrentTimeMilliseconds()
		sequence := nextSequenceNumberForMilliseconds(stream, milliseconds)
		return formatEntryID(milliseconds, sequence)
	}

	if !isPartialAutoGeneratedEntryID(entryID) {
		return entryID
	}

	parts := strings.Split(entryID, "-")
	milliseconds, err := strconv.ParseInt(parts[0], 10, 64)
	if err != nil {
		return entryID
	}

	sequence := nextSequenceNumberForMilliseconds(stream, milliseconds)
	return formatEntryID(milliseconds, sequence)
}
